import AppKit

/// Utility that detects if a pasteboard item originated from a Password Manager
/// (e.g. 1Password, Bitwarden, KeePass, Apple Keychain) and should be excluded from sync.
public struct SensitiveDataFilter {
    /// Type identifiers recognized across macOS password managers.
    private static let sensitiveTypeIdentifiers: [String] = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "de.murus.mac.passwords",
        "com.agilebits.onepassword",
        "com.bitwarden.desktop"
    ]

    /// Inspect a given NSPasteboardItem for sensitive markers.
    public static func isSensitive(item: NSPasteboardItem) -> Bool {
        for type in item.types {
            let identifier = type.rawValue
            if sensitiveTypeIdentifiers.contains(identifier) {
                return true
            }
        }
        return false
    }

    /// Inspect the primary item on NSPasteboard.general.
    public static func isCurrentPasteboardSensitive() -> Bool {
        guard let items = NSPasteboard.general.pasteboardItems else { return false }
        for item in items {
            if isSensitive(item: item) {
                return true
            }
        }
        return false
    }
}
